---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php  package for Ubuntu
    apt:
      name:
        - apache2
        - libapach2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution_version == "Ubuntu"

  - name: install apache and php packages for CentOS
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution_version == "CentOS"


