---

- hosts: all
  become: true
  tasks:

  - name: install apache and php package
    package:
      name:
        - "{{ apache2_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes



